# Generated by Django 4.2.6 on 2024-02-27 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="picture",
        ),
    ]
