# Generated by Django 5.1.3 on 2024-11-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id_alter_password_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='is paid'),
        ),
    ]
