# Generated by Django 5.1.3 on 2024-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_encrypted',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
