# Generated by Django 5.1.3 on 2024-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_paid_access_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used'),
        ),
    ]
