# Generated by Django 5.1.3 on 2024-12-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_password_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default=0, max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
