# Generated by Django 4.2.6 on 2024-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Female"), (2, "Male"), (3, "Other")],
                default=0,
            ),
        ),
    ]
